name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main,  master ]

env:
  IMAGE_NAME: "crud-server"
  CONTAINER_NAME: "crud-server-container"

jobs:
  image_build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: docker build -t auth:v1 -f Dockerfile .
      
      - name: Run Docker container
        run: |
          docker run -d --name auth-container -p 50051:50051 auth:v1
          sleep 5
      
      - name: Cleanup
        run: |
          docker stop auth-container
          docker rm auth-container
